---
- name: Install uno from scratch
  hosts: uvns
  vars:
    uno_installer_dir: "/tmp"
    uno_installer_path: "/tmp/uno.installer.sh"
    uno_installer_url: https://uno.mentalsmash.org/install
    uno_dir_v: "{{uno_dir | default('/opt/uno')}}"
    uno_archives_dir: "{{lookup('env', 'UNO_ARCHIVES') | default('.') }}"
  tasks:
    - name: Delete previous installers
      file:
        path: "{{uno_installer_path}}"
        state: absent
    - name: Download uno installer
      get_url:
        url: "{{uno_installer_url}}"
        dest: "{{uno_installer_path}}"
        mode: '0700'
        validate_certs: no
    - name: Copy connextdds-py wheel
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_py}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_py | default('')"
    - name: Copy RTI Connext DDS host installer
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_host}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_host | default('')"
    - name: Copy RTI Connext DDS target installer
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_target}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_target | default('')"
    - name: Wipe previous installations
      become: yes
      file:
        path: "{{uno_dir_v}}"
        state: absent
    - name: Run uno installer
      shell:
        chdir: "{{uno_installer_dir}}"
        cmd: >
          NONINTERACTIVE=y
          UNO_DIR='{{uno_dir_v}}'
          {{uno_installer_path}}
    - name: Delete connextdds-py wheel
      file:
        path: "{{uno_installer_dir}}/{{connextdds_py}}"
        state: absent
    - name: Delete RTI Connext DDS host
      file:
        path: "{{uno_installer_dir}}/{{connextdds_host}}"
        state: absent
    - name: Delete RTI Connext DDS taget
      file:
        path: "{{uno_installer_dir}}/{{connextdds_target}}"
        state: absent
    

- import_playbook: uno-check.yml
...
