---
- name: Install uno from scratch
  hosts: "{{ uvns | default('uvns')}}"
  vars:
    uno_installer_dir: "/tmp"
    uno_installer_path: "/tmp/uno.installer.sh"
    uno_installer_url: https://uno.mentalsmash.org/install
    uno_install_path_v: "{{uno_install_path | default('/opt/uno')}}"
    uno_archives_dir: "{{lookup('env', 'UNO_ARCHIVES') | default('.') }}"
  tasks:
    - name: Delete previous installers
      file:
        path: "{{uno_installer_path}}"
        state: absent
    - name: Download uno installer
      get_url:
        url: "{{uno_installer_url}}"
        dest: "{{uno_installer_path}}"
        mode: '0700'
        validate_certs: no
    - name: Copy connextdds-py wheel
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_py}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_py | default('')"
    - name: Copy RTI Connext DDS host installer
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_host}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_host | default('')"
    - name: Copy RTI Connext DDS target installer
      synchronize:
        src: "{{uno_archives_dir}}/{{connextdds_target}}"
        dest: "{{uno_installer_dir}}"
      when: "connextdds_target | default('')"
    - name: Wipe previous installations
      become: yes
      file:
        path: "{{uno_install_path_v}}"
        state: absent
    - name: Run uno installer
      shell:
        chdir: "{{uno_installer_dir}}"
        cmd: >
          NONINTERACTIVE=y
          UNO_DIR='{{uno_install_path_v}}'
          {{uno_installer_path}}

- import_playbook: uno-check.yml
...
