---
- name: Distribute UVN to registry
  hosts: registry
  vars:
    uvn_dir: >-
      /home/{{ansible_user}}/{{uvn}}
    uvn_profile: >-
      /home/{{ansible_user}}/.uvn.profile
    profile: >-
      /home/{{ansible_user}}/.profile
  tasks:
    - name: Synchronize UVN files
      synchronize:
        src: "{{ lookup('env', 'UVN_DIR') }}"
        dest: "{{uvn_dir}}"
        delete: yes
        rsync_opts:
          - "--exclude=S.gpg-agent"
    - name: Create .uvn.profile
      template:
        src: templates/uvn.profile
        dest: "{{uvn_profile}}"
        mode: 0700
      tags: profile
    - name: Load .uvn.profile from .profile
      lineinfile:
        path: "{{profile}}"
        regexp: "uvn.profile$"
        line: ". {{uvn_profile}}"
      tags: profile
- name: Distribute UVN to cells
  hosts: cells
  vars:
    uvn_dir: >-
      /home/{{ansible_user}}/{{cell}}@{{uvn}}
    uvn_profile: >-
      /home/{{ansible_user}}/.uvn.profile
    profile: >-
      /home/{{ansible_user}}/.profile
    cell_installers_src: >-
      {{ lookup('env', 'UVN_DIR') }}/installers/uvn-{{uvn}}-*-{{cell}}.zip
    cell_installers_dst: >-
      /home/{{ansible_user}}/
    bootstrap_zip: >-
      /home/{{ansible_user}}/uvn-{{uvn}}-bootstrap-{{cell}}.zip
    latest_zip: >-
      /home/{{ansible_user}}/uvn-{{uvn}}-latest-{{cell}}.zip
  tasks:
    - name: Delete UVN files
      file:
        path: "{{uvn_dir}}"
        state: absent
    - name: Copy UVN installers
      synchronize:
        src: "{{item}}"
        dest: "{{cell_installers_dst}}"
      with_fileglob:
        - "{{cell_installers_src}}"
    - name: Install boostrap package
      shell: >
        uvn I {{bootstrap_zip}} {{uvn_dir}}
    - name: Install latest deployment package
      shell: >
        cd {{uvn_dir}} && uvn I {{latest_zip}} .
    - name: Create .uvn.profile
      template:
        src: templates/uvn.profile
        dest: "{{uvn_profile}}"
        mode: 0700
      tags: profile
    - name: Load .uvn.profile from .profile
      lineinfile:
        path: "{{profile}}"
        regexp: "uvn.profile$"
        line: ". {{uvn_profile}}"
      tags: profile
    - name: List cell installers
      shell: "ls {{cell_installers_dst}}/uvn-{{uvn}}-*-{{cell}}.zip"
      register: cell_installers
    - name: Delete cell installers
      file:
        path: "{{item}}"
        state: absent
      with_items: "{{cell_installers.stdout_lines}}"
...
