---
- name: Start UVN agent on registry
  hosts: registry
  tasks:
    - name: Start a new agent process
      shell: ". /home/{{ansible_user}}/.uvn.profile && cd ${UVN_DIR} && sudo nohup uvn A -v </dev/null >/dev/null 2>&1 &"
- name: Start UVN agents on cells
  hosts: cells
  tasks:
    - name: Start a new agent process
      shell: ". /home/{{ansible_user}}/.uvn.profile && cd ${UVN_DIR} && sudo nohup uvn A -v {{interfaces}} </dev/null >/dev/null 2>&1 &"
...
