---
- name: Start UVN agent on registry
  hosts: registry
  tasks:
    - name: Start a new agent process
      shell: ". $(which uvnd.profile) && uvnd_start"
- name: Start UVN agents on cells
  hosts: cells
  tasks:
    - name: Start a new agent process
      shell: ". $(which uvnd.profile) && uvnd_cell '{{interfaces}}'"
...
