---
- name: Check required variables
  hosts: "{{ uvns | default('uvns')}}"
  vars:
    tgt_uvn_dir: "{{lookup('env', 'UVN_DIR')}}"
    tgt_uvn: "{{uvn | default('')}}"
  tasks:
    - name: Check environment variable 'UVN_DIR'
      fail:
        msg: "Required environment variable not set: 'UVN_DIR'"
      when: not tgt_uvn_dir
    - name: Check variable 'uvn'
      fail:
        msg: "Required variable not set: 'uvn'"
      when: not tgt_uvn
- name: Distribute UVN to registry
  hosts: "{{ registry | default('registry')}}"
  vars:
    uvn_dir: "/home/{{ansible_user}}/{{uvn}}"
  tasks:
    - name: Delete UVN files from registry
      file:
        path: "{{uvn_dir}}"
        state: absent
    - name: Copy UVN files to registry
      synchronize:
        src: "{{ lookup('env', 'UVN_DIR') }}"
        dest: "{{uvn_dir}}"
        rsync_opts:
          - "--exclude=S.gpg-agent"
- name: Distribute UVN to cells
  hosts: "{{ cells | default('cells')}}"
  vars:
    uvn_dir: "/home/{{ansible_user}}/{{cell}}@{{uvn}}"
    bootstrap_zip: "/home/{{ansible_user}}/uvn-{{uvn}}-bootstrap-{{cell}}.zip"
  tasks:
    - name: Delete UVN files from cell
      file:
        path: "{{uvn_dir}}"
        state: absent
    - name: Copy UVN installer to cell
      copy:
        src: "{{ lookup('env', 'UVN_DIR') }}/installers/uvn-{{uvn}}-bootstrap-{{cell}}.zip"
        dest: "{{bootstrap_zip}}"
    - name: Install cell package
      shell: >
        uvn I {{bootstrap_zip}} {{uvn_dir}}
...
