name: Release Step (Push Image)
run-name: |
  release (${{inputs.flavor}}) - push image [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      flavor:
        type: string
        required: true
      tags-config:
        type: string
        required: true
      flavor-config:
        type: string
        required: true

concurrency:
  group: release-push-images-${{ github.ref }}-${{ inputs.flavor }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true
      
      - name: Extract image metadata
        id: meta-docker
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: ${{ inputs.tags-config }}
          flavor: ${{ inputs.flavor-config }}
    
      - name: Log in to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish images
        run: |
          docker image pull ${{inputs.tag}}

          images="$(echo ${{steps.meta-docker.outputs.tags}} | tr , ' ')"
          for tag in ${images}; do
            docker image tag ${{inputs.tag}} ${tag}
          done
          for tag in ${images}; do
            docker image push ${tag}
          done
