name: nightly
run-name: Build & test ${{ github.ref_type }} ${{ github.ref_name }}

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


concurrency:
  # Don't run workflow in parallel for the same branch/tag
  group: ${{ github.workflow }}${{ github.ref }}


jobs:
  build_and_test:
    strategy:
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04"] #, "debian:stable"]
        uno-middleware: [uno.middleware.native, uno_middleware_connext]
        exclude:
          - base-image: ubuntu:24.04
            uno-middleware: uno_middleware_connext
          # - base-image: debian:stable
          #   uno-middleware: uno_middleware_connext
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}


  push_images:
    if: github.ref_name	== 'master'
    needs: build_and_test
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      tag-default: nightly
      tag-static:  nightly
      badge-default-version: "e7aab205f782cc0c6f394a2fece90509"
      badge-default-base:    "8f31c46dcfd0543b42f356e5b1c6c2c8"
      badge-static-version:  "b310f08c34f051846877aeb59b0be311"
      badge-static-base:     "b0e38a84eb8679d5212e162fbb616773"

