name: Release CI
run-name: Release from tag ${{ github.ref_name }}

on:
  workflow_dispatch:

  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /


concurrency:
  group: '${{ github.workflow }}'


jobs:
  build_test_release:
    uses: ./.github/workflows/release.yml
    secrets: inherit

