name: CI (Full)

on:
  workflow_dispatch:


concurrency:
  group: ci-build-full-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-n-test:
    strategy:
      matrix:
        build-platform: [amd64, arm64]
        base-image: [ubuntu:22.04]
        uno-middleware: [uno_middleware_connext, uno.middleware.native]
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      build-platform: ${{matrix.build-platform}}
      base-image: ${{matrix.base-image}}
      uno-middleware: ${{matrix.uno-middleware}}

