name: Deb Release
run-name: |
  deb release [${{github.ref_name}}]

on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: deb-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  build-packages:
    strategy:
      matrix:
        builder-tag: ["ubuntu-22.04", "ubuntu-24.04"]
    runs-on: ubuntu-latest
    steps:
    - name: Clone uno
      uses: actions/checkout@v4
      with:
        path: src/uno
        submodules: true

    - name: Log in to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build packages
      run: |
        docker run --rm \
          -v $(pwd)/src/uno:/uno \
          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
          /uno/scripts/debian_build.sh

    - name: Fix permissions
      run: |
        docker run --rm \
          -v $(pwd)/src/uno:/uno \
          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
          chown -R $(id -u):$(id -g) /uno
      if: always()

    - name: Upload uno packages
      uses: actions/upload-artifact@v4
      with:
        name: uno
        path: src/uno/debian-dist/uno_*
      
    - name: Upload uno-static packages
      uses: actions/upload-artifact@v4
      with:
        name: uno-static
        path: src/uno/debian-dist/uno-static_*


  build-packages-arm64:
    strategy:
      matrix:
        builder-tag: ["ubuntu-22.04"]
    runs-on: ["self-hosted", "linux", "arm64", "rpi5"]
    steps:
    - name: Clone uno
      uses: actions/checkout@v4
      with:
        path: src/uno
        submodules: true

    - name: Log in to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build packages
      run: |
        docker run --rm \
          -v $(pwd)/src/uno:/uno \
          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
          /uno/scripts/debian_build.sh

    - name: Fix permissions
      run: |
        docker run --rm \
          -v $(pwd)/src/uno:/uno \
          ghcr.io/mentalsmash/uno-ci-debian-builder:${{ matrix.builder-tag }} \
          chown -R $(id -u):$(id -g) /uno
      if: always()

    - name: Upload uno packages
      uses: actions/upload-artifact@v4
      with:
        name: uno-arm64
        path: src/uno/debian-dist/uno_*
      
    - name: Upload uno-static packages
      uses: actions/upload-artifact@v4
      with:
        name: uno-static-arm64
        path: src/uno/debian-dist/uno-static_*


  publish_release:
    needs:
      - build-packages
      - build-packages-arm64
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          uno/*.deb
          uno-arm64/*.deb
          uno-static/*.deb
          uno-static-arm64/*.deb
