name: Deb Release
run-name: |
  deb release [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_dispatch:

  push:
    tags:
      - '*'
      - '!*/**'

  workflow_run:
    workflows: ["Release (default)"]
    types: [completed]

concurrency:
  group: deb-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read

jobs:
  check-trigger:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    outputs:
      DO_BUILD: ${{steps.config.outputs.DO_BUILD}}
    steps:
      - name: "Generate test configuration"
        id: config
        run: |
          do_build=y
          case "${{github.ref_type}}" in
            tag)
              ;;
            branch)
              case "${{github.ref_name}}" in
                master)
                  ;;
                *)
                do_build=
                  ;;
              esac
              ;;
          esac
          (
            echo DO_BUILD=${do_build}
          ) >> ${GITHUB_OUTPUT}
      - name: "Fail if upstream job failed"
        run: |
          echo "upstream job for ${{github.ref_type}} ${{github.ref_name}} failed with conclusion '${{github.event.workflow_run.conclusion}}'"
          exit 1
        if: steps.config.outputs.DO_BUILD && github.event.workflow_run.conclusion != 'success'

  build-packages:
    needs: check-trigger
    if: needs.check-trigger.outputs.DO_BUILD
    strategy:
      matrix:
        base-tag: ["ubuntu:22.04"]
        platform: [amd64, arm64]
    uses: ./.github/workflows/_deb_build.yml
    with:
      base-tag: ${{ matrix.base-tag }}
      platform: ${{ matrix.platform }}

  publish_release:
    needs: build-packages
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          uno/*.deb
          uno-arm64/*.deb
