name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          push: true
          tags: mentalsmash/uno:dev
          build-args: |
            DEV=y
            EXTRAS=y
      
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          push: true
          tags: mentalsmash/uno:latest

