name: Install Test
run-name: |
  install test [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: Platforms to test (JSON array)
        type: string
        required: true
      tag:
        description: Image tag to test (e.g. mentalsmash/uno:latest)
        type: string

  workflow_run:
    workflows: ["Release"]
    types: [completed]

concurrency:
  group: install-test-default-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-trigger:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    outputs:
      DO_VALIDATE: ${{steps.config.outputs.DO_VALIDATE}}
      IMAGE_TAG: ${{steps.config.outputs.IMAGE_TAG}}
    steps:
      - name: "Generate test configuration"
        id: config
        run: |
          do_validate=y
          case "${{github.ref_type}}" in
            tag)
              image_tag=latest
              ;;
            branch)
              case "${{github.ref_name}}" in
                master)
                  image_tag=nightly
                  ;;
                *)
                  do_validate=
                  ;;
              esac
              ;;
          esac
          (
            echo IMAGE_TAG=${image_tag}
            echo DO_VALIDATE=${do_validate}
          ) >> ${GITHUB_OUTPUT}
      - name: "Fail if upstream job failed"
        run: |
          echo "upstream job for ${{github.ref_type}} ${{github.ref_name}} failed with conclusion '${{github.event.workflow_run.conclusion}}'"
          exit 1
        if: steps.config.outputs.DO_VALIDATE && github.event.workflow_run.conclusion != 'success'

  test-trigger:
    needs: check-trigger
    if: needs.check-trigger.outputs.DO_VALIDATE
    strategy:
      matrix:
        platform: [amd64, arm64]
        install-rti-license: [true, false]
    uses: ./.github/workflows/_install_test.yml
    secrets: inherit
    with:
      tag: ${{github.repository}}:${{ needs.check-trigger.outputs.IMAGE_TAG }}
      platform: ${{matrix.platform}}
      install-rti-license: ${{matrix.install-rti-license}}

  test-user:
    if: github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
        install-rti-license: [true, false]
    uses: ./.github/workflows/_install_test.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      platform: ${{matrix.platform}}
      install-rti-license: ${{matrix.install-rti-license}}

