name: Install Test (static)
run-name: |
  install test (static) [${{github.ref_type == 'branch' && 'nightly' || 'stable'}} from ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: Platforms to test (JSON array)
        type: string
        required: true
      tag:
        description: Image tag to test (e.g. mentalsmash/uno:latest-static)
        type: string
        required: true

  workflow_run:
    workflows: ["Release (static)"]
    types: [completed]

concurrency:
  group: install-test-static-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-trigger:
    if: github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    outputs:
      DO_VALIDATE: ${{steps.run-config.outputs.DO_VALIDATE}}
      IMAGE_TAG: ${{steps.run-config.outputs.IMAGE_TAG}}
    steps:
      - name: "Ignore non-release upstream jobs"
        id: run-config
        run: |
          do_validate=y
          case ${{github.ref_type}} in
            tag)
              image_tag=latest
              ;;
            branch)
              case ${{github.ref_name}} in
                master)
                  image_tag=nightly
                  ;;
                *)
                  do_validate=
                  ;;
              esac
              ;;
          esac
          echo (
            echo IMAGE_TAG=${image_tag}
            echo DO_VALIDATE=${do_validate}
          ) >> ${GITHUB_OUTPUT}
      - name: "Fail if upstream job failed"
        run: |
          echo "upstream job for ${{github.ref_type}} ${{github.ref_name}} failed with conclusion '${{github.event.workflow_run.conclusion}}'"
          exit 1
        if: steps.run-config.outputs.DO_VALIDATE && github.event.workflow_run.conclusion != 'success'

  test-trigger:
    needs: check-trigger
    if: needs.check-trigger.outputs.DO_VALIDATE
    strategy:
      matrix:
        platform: [amd64, arm64]
    uses: ./.github/workflows/_install_test.yml
    with:
      tag: ${{github.repository}}:${{ needs.check-trigger.outputs.IMAGE_TAG }}
      platform: ${{matrix.platform}}
      flavor: static

  test-user:
    if: github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
    uses: ./.github/workflows/_install_test.yml
    with:
      tag: ${{ inputs.tag }}
      platform: ${{matrix.platform}}
      flavor: static

