name: Pull Request (Closed)
run-name: |
  PR #${{github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number}} [closed, ${{ ((github.event_name == 'pull_request' && github.event.pull_request.merged) || inputs.pr-merged) && 'merged' || 'rejected' }}${{ github.event_name != 'pull_request' && ', manual trigger' || '' }}] ${{github.event_name == 'pull_request' && github.event.pull_request.title || ''}}

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      pr-number:
        description: "PR #"
        type: number
        required: true
      pr-merged:
        description: "Whether the PR was merged or not"
        type: boolean
        default: false


concurrency:
  group: pr-closed-${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number }}
  cancel-in-progress: false

permissions:
  actions: write
  packages: read

jobs:
  cleanup_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true
      
      - name: Log in to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Clean up workflow runs"
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -e GH_TOKEN=${GH_TOKEN} \
            -w /workspace \
            ${ADMIN_IMAGE} \
            src/uno/scripts/ci-admin pr-closed \
              -r ${{ github.repository }} \
              -N ${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number }} \
              ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged || inputs.pr-merged) && '-m' || '' }}
        env:
          # Changes to actions (e.g. delete workflow runs) require a PAT, and don't work with the GITHUB_TOKEN
          # see https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#delete-a-workflow-run
          GH_TOKEN: ${{ secrets.UNO_CI_ADMIN_PAT }}
          ADMIN_IMAGE: ghcr.io/mentalsmash/uno-ci-admin:latest

