name: Build and push images (release)

on:
  workflow_call:

concurrency:
  # Don't run workflow in parallel
  group: ${{ github.workflow }}

env:
  TAG_DEFAULT: latest
  TAG_STATIC:  latest-static
  BASE_IMAGE_DEFAULT: ubuntu:22.04
  BASE_IMAGE_STATIC: ubuntu:24.04
  MIDDLEWARE_DEFAULT: uno_middleware_connext
  MIDDLEWARE_STATIC: uno.middleware.native
  BADGE_DEFAULT_VERSION: "29b57b0427def87cc3ef4ab81c956c29"
  BADGE_DEFAULT_BASE:    "2d53344e1ccfae961665e08432f18113"
  BADGE_STATIC_VERSION:  "d73e338805c7d2c348a2d7149a66f66c"
  BADGE_STATIC_BASE:     "373e55438055b1222c9937797c949f9b"

jobs:
  push_images:
    uses: ./.github/workflows/push_images.yml
    secrets: inherit
    with:
      tag-default: ${{ env.TAG_DEFAULT }}
      tag-static:  ${{ env.TAG_STATIC }}
      base-image-default: ${{ env.BASE_IMAGE_DEFAULT }}
      base-image-static: ${{ env.BASE_IMAGE_STATIC }}
      middleware-default: ${{ env.MIDDLEWARE_DEFAULT }}
      middleware-static: ${{ env.MIDDLEWARE_STATIC }}


  update_badges:
    needs: push_images
    uses: ./.github/workflows/update_image_badges.yml
    secrets: inherit
    with:
      tag-default: ${{ env.TAG_DEFAULT }}
      tag-static:  ${{ env.TAG_STATIC }}
      base-image-default: ${{ env.BASE_IMAGE_DEFAULT }}
      base-image-static: ${{ env.BASE_IMAGE_STATIC }}
      badge-default-version: ${{ env.BADGE_DEFAULT_VERSION }}
      badge-default-base: ${{ env.BADGE_DEFAULT_BASE }}
      badge-static-version: ${{ env.BADGE_STATIC_VERSION }}
      badge-static-base: ${{ env.BADGE_STATIC_BASE }}


  update_release_badge:
    runs-on: ubuntu-latest
    needs: push_images
    steps:
    - uses: actions/checkout@v4

    - name: Generate derived variables
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Update latest-release badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE_TOKEN }}
        gistID: "fb644ccb3cbb57b2636f9eca808b9931"
        filename: uno-badge-latest-release.json
        label: latest release
        message: ${{ github.ref_name }}${{ github.ref_type == 'branch' && '@' || '' }}${{ github.ref_type == 'branch' && steps.vars.outputs.sha_short || '' }}
        color: ${{ github.ref_type == 'tag' && 'green' || 'orange' }}

