name: Release to Docker

on:
  workflow_dispatch:

  workflow_call:

  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

concurrency:
  group: '${{ github.workflow }}'


env:
  LATEST_TAG: mentalsmash/uno:latest
  LATEST_STATIC_TAG: mentalsmash/uno:latest-static

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: mentalsmash/uno

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push full image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: mentalsmash/uno:latest,mentalsmash/uno:${{ github.ref_name }}
          push: true
          context: .
          build-args: |
            UNO_MIDDLEWARE=uno_middleware_connext
            BASE_IMAGE=ubuntu:22.04

      - name: Build and push static image
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          tags: mentalsmash/uno:latest-static,mentalsmash/uno:${{ github.ref_name }}-static
          push: true
          context: .
          build-args: |
            UNO_MIDDLEWARE=uno.middleware.native
            BASE_IMAGE=ubuntu:latest      


