name: Generate Release
run-name: Build, test, and release ${{ github.ref_type }} ${{ github.ref_name }}${{ github.ref_type == 'branch' && ' @ ' + github.sha || '' }}

on:
  workflow_call:


concurrency:
  group: ${{ github.workflow }} for ${{ github.ref_type }} ${{ github.ref_name }}


jobs:
  build_and_test:
    strategy:
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04"]
        uno-middleware: [uno.middleware.native, uno_middleware_connext]
        exclude:
          - base-image: ubuntu:22.04
            uno-middleware: uno.middleware.native
          - base-image: ubuntu:24.04
            uno-middleware: uno_middleware_connext
    uses: ./.github/workflows/build_and_test.yml
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}

  docker_images:
    needs: build_and_test
    uses: ./.github/workflows/build_and_push_images.yml

