name: Release
run-name: ${{github.ref_type == 'tag' && 'Stable' || 'Nightly' }} release from ${{github.ref_type}} ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}

on:
  push:
    branches:
      - master
    tags:
      - '*'
      - '!*/**'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  flavors:
    strategy:
      matrix:
        include:
          - base-image: ubuntu:22.04
            flavor: default
            base-tag: ${{github.ref_type == 'branch' && 'nightly' || 'latest'}}
          - base-image: ubuntu:24.04
            flavor: static
            base-tag: ${{github.ref_type == 'branch' && 'nightly' || 'latest'}}
    uses: ./.github/workflows/release_flavor.yml
    with:
      flavor: ${{matrix.flavor}}
      base-image: ${{matrix.base-image}}
      base-tag: ${{matrix.base-tag}}

  update_badges:
    needs: flavors
    uses: ./.github/workflows/release_badges.yml
    secrets: inherit
    with:
      base-image-static: ubuntu:24.04
      base-image-default: ubuntu:22.04

